import { TAG_TYPE } from '@/entity';
import { MigrationInterface, QueryRunner } from 'typeorm';

export class createWeaponTag1652837885040 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const weaponList = [
      {
        id: 72,
        name: 'Primordial Jade Winged-Spear',
        slug: 'primordial-jade-winged-spear',
        rarity: '5',
        atk: 48,
        obtain: 'gacha',
        type: 'polearm',
      },
      {
        id: 74,
        name: 'Skyward Spine',
        slug: 'skyward-spine',
        rarity: '5',
        atk: 48,
        obtain: 'gacha',
        type: 'polearm',
      },
      {
        id: 76,
        name: 'Aquila Favonia',
        slug: 'aquila-favonia',
        rarity: '5',
        atk: 48,
        obtain: 'gacha',
        type: 'sword',
      },
      {
        id: 2,
        name: 'Amos Bow',
        slug: 'amos-bow',
        rarity: '5',
        atk: 46,
        obtain: 'gacha',
        type: 'bow',
      },
      {
        id: 60,
        name: 'Wolfs Gravestone',
        slug: 'wolfs-gravestone',
        rarity: '5',
        atk: 46,
        obtain: 'gacha',
        type: 'claymore',
      },
      {
        id: 70,
        name: 'Kunwus Iris Rift',
        slug: 'kunwus-iris-rift',
        rarity: '5',
        atk: 46,
        obtain: 'gacha',
        type: 'polearm',
      },
      {
        id: 17,
        name: 'Skyward Harp',
        slug: 'skyward-harp',
        rarity: '5',
        atk: 45,
        obtain: 'gacha',
        type: 'bow',
      },
      {
        id: 35,
        name: 'Skyward Atlas',
        slug: 'skyward-atlas',
        rarity: '5',
        atk: 45,
        obtain: 'gacha',
        type: 'catalyst',
      },
      {
        id: 55,
        name: 'Skyward Pride',
        slug: 'skyward-pride',
        rarity: '5',
        atk: 45,
        obtain: 'gacha',
        type: 'claymore',
      },
      {
        id: 3,
        name: 'Blackcliff Warbow',
        slug: 'blackcliff-warbow',
        rarity: '4',
        atk: 44,
        obtain: 'starglitter exchange',
        type: 'bow',
      },
      {
        id: 27,
        name: 'Lost Prayer to the Sacred Winds',
        slug: 'lost-prayer-to-the-sacred-winds',
        rarity: '5',
        atk: 44,
        obtain: 'gacha',
        type: 'catalyst',
      },
      {
        id: 29,
        name: 'Mappa Mare',
        slug: 'mappa-mare',
        rarity: '4',
        atk: 44,
        obtain: 'crafting',
        type: 'catalyst',
      },
      {
        id: 33,
        name: 'Royal Grimoire',
        slug: 'royal-grimoire',
        rarity: '4',
        atk: 44,
        obtain: 'starglitter exchange',
        type: 'catalyst',
      },
      {
        id: 48,
        name: 'Prototype Aminus',
        slug: 'prototype-aminus',
        rarity: '4',
        atk: 44,
        obtain: 'crafting',
        type: 'claymore',
      },
      {
        id: 52,
        name: 'Sacrificial Greatsword',
        slug: 'sacrificial-greatsword',
        rarity: '4',
        atk: 44,
        obtain: 'gacha',
        type: 'claymore',
      },
      {
        id: 64,
        name: 'Crescent Pike',
        slug: 'crescent-pike',
        rarity: '4',
        atk: 44,
        obtain: 'crafting',
        type: 'polearm',
      },
      {
        id: 67,
        name: 'Favonius Lance',
        slug: 'favonius-lance',
        rarity: '4',
        atk: 44,
        obtain: 'gacha',
        type: 'polearm',
      },
      {
        id: 77,
        name: 'Blackcliff Longsword',
        slug: 'blackcliff-longsword',
        rarity: '4',
        atk: 44,
        obtain: 'starglitter exchange',
        type: 'sword',
      },
      {
        id: 86,
        name: 'Prototype Rancour',
        slug: 'prototype-rancour',
        rarity: '4',
        atk: 44,
        obtain: 'crafting',
        type: 'sword',
      },
      {
        id: 91,
        name: 'Skyward Blade',
        slug: 'skyward-blade',
        rarity: '5',
        atk: 44,
        obtain: 'gacha',
        type: 'sword',
      },
      {
        id: 92,
        name: 'The Alley Flash',
        slug: 'the-alley-flash',
        rarity: '4',
        atk: 44,
        obtain: 'gacha',
        type: 'sword',
      },
      {
        id: 14,
        name: 'Sacrificial Bow',
        slug: 'sacrificial-bow',
        rarity: '4',
        atk: 43,
        obtain: 'gacha',
        type: 'bow',
      },
      {
        id: 51,
        name: 'Royal Greatsword',
        slug: 'royal-greatsword',
        rarity: '4',
        atk: 43,
        obtain: 'starglitter exchange',
        type: 'claymore',
      },
      {
        id: 9,
        name: 'Prototype Crescent',
        slug: 'prototype-crescent',
        rarity: '4',
        atk: 42,
        obtain: 'crafting',
        type: 'bow',
      },
      {
        id: 12,
        name: 'Royal Bow',
        slug: 'royal-bow',
        rarity: '4',
        atk: 42,
        obtain: 'starglitter exchange',
        type: 'bow',
      },
      {
        id: 13,
        name: 'Rust',
        slug: 'rust',
        rarity: '4',
        atk: 42,
        obtain: 'gacha',
        type: 'bow',
      },
      {
        id: 19,
        name: 'The Stringless',
        slug: 'the-stringless',
        rarity: '4',
        atk: 42,
        obtain: 'gacha',
        type: 'bow',
      },
      {
        id: 20,
        name: 'The Viridescent Hunt',
        slug: 'the-viridescent-hunt',
        rarity: '4',
        atk: 42,
        obtain: 'bp bounty',
        type: 'bow',
      },
      {
        id: 23,
        name: 'Blackcliff Amulet',
        slug: 'blackcliff-amulet',
        rarity: '4',
        atk: 42,
        obtain: 'starglitter exchange',
        type: 'catalyst',
      },
      {
        id: 26,
        name: 'Favonius Codex',
        slug: 'favonius-codex',
        rarity: '4',
        atk: 42,
        obtain: 'gacha',
        type: 'catalyst',
      },
      {
        id: 32,
        name: 'Prototype Malice',
        slug: 'prototype-malice',
        rarity: '4',
        atk: 42,
        obtain: 'crafting',
        type: 'catalyst',
      },
      {
        id: 36,
        name: 'Solar Pearl',
        slug: 'solar-pearl',
        rarity: '4',
        atk: 42,
        obtain: 'bp bounty',
        type: 'catalyst',
      },
      {
        id: 37,
        name: 'The Widsith',
        slug: 'the-widsith',
        rarity: '4',
        atk: 42,
        obtain: 'gacha',
        type: 'catalyst',
      },
      {
        id: 40,
        name: 'Wine and Song',
        slug: 'wine-and-song',
        rarity: '4',
        atk: 42,
        obtain: 'gacha',
        type: 'catalyst',
      },
      {
        id: 41,
        name: 'Blackcliff Slasher',
        slug: 'blackcliff-slasher',
        rarity: '4',
        atk: 42,
        obtain: 'starglitter exchange',
        type: 'claymore',
      },
      {
        id: 50,
        name: 'Rainslasher',
        slug: 'rainslasher',
        rarity: '4',
        atk: 42,
        obtain: 'gacha',
        type: 'claymore',
      },
      {
        id: 53,
        name: 'Serpent Spine',
        slug: 'serpent-spine',
        rarity: '4',
        atk: 42,
        obtain: 'bp bounty',
        type: 'claymore',
      },
      {
        id: 56,
        name: 'The Bell',
        slug: 'the-bell',
        rarity: '4',
        atk: 42,
        obtain: 'gacha',
        type: 'claymore',
      },
      {
        id: 59,
        name: 'Whiteblind',
        slug: 'whiteblind',
        rarity: '4',
        atk: 42,
        obtain: 'crafting',
        type: 'claymore',
      },
      {
        id: 63,
        name: 'Blackcliff Pole',
        slug: 'blackcliff-pole',
        rarity: '4',
        atk: 42,
        obtain: 'starglitter exchange',
        type: 'polearm',
      },
      {
        id: 71,
        name: 'Lithic Spear',
        slug: 'lithic-spear',
        rarity: '4',
        atk: 42,
        obtain: 'gacha',
        type: 'polearm',
      },
      {
        id: 73,
        name: 'Prototype Grudge',
        slug: 'prototype-grudge',
        rarity: '4',
        atk: 42,
        obtain: 'crafting',
        type: 'polearm',
      },
      {
        id: 84,
        name: 'Iron Sting',
        slug: 'iron-sting',
        rarity: '4',
        atk: 42,
        obtain: 'crafting',
        type: 'sword',
      },
      {
        id: 85,
        name: 'Lions Roar',
        slug: 'lions-roar',
        rarity: '4',
        atk: 42,
        obtain: 'gacha',
        type: 'sword',
      },
      {
        id: 87,
        name: 'Royal Longsword',
        slug: 'royal-longsword',
        rarity: '4',
        atk: 42,
        obtain: 'starglitter exchange',
        type: 'sword',
      },
      {
        id: 93,
        name: 'The Black Sword',
        slug: 'the-black-sword',
        rarity: '4',
        atk: 42,
        obtain: 'bp bounty',
        type: 'sword',
      },
      {
        id: 94,
        name: 'The Flute',
        slug: 'the-flute',
        rarity: '4',
        atk: 42,
        obtain: 'gacha',
        type: 'sword',
      },
      {
        id: 1,
        name: 'Alley Hunter',
        slug: 'alley-hunter',
        rarity: '4',
        atk: 41,
        obtain: 'gacha',
        type: 'bow',
      },
      {
        id: 4,
        name: 'Compound Bow',
        slug: 'compound-bow',
        rarity: '4',
        atk: 41,
        obtain: 'crafting',
        type: 'bow',
      },
      {
        id: 6,
        name: 'Favonius Warbow',
        slug: 'favonius-warbow',
        rarity: '4',
        atk: 41,
        obtain: 'gacha',
        type: 'bow',
      },
      {
        id: 25,
        name: 'Eye of Perception',
        slug: 'eye-of-perception',
        rarity: '4',
        atk: 41,
        obtain: 'gacha',
        type: 'catalyst',
      },
      {
        id: 34,
        name: 'Sacrificial Fragments',
        slug: 'sacrificial-fragments',
        rarity: '4',
        atk: 41,
        obtain: 'gacha',
        type: 'catalyst',
      },
      {
        id: 44,
        name: 'Favonius Greatsword',
        slug: 'favonius-greatsword',
        rarity: '4',
        atk: 41,
        obtain: 'gacha',
        type: 'claymore',
      },
      {
        id: 46,
        name: 'Lithic Blade',
        slug: 'lithic-blade',
        rarity: '4',
        atk: 41,
        obtain: 'gacha',
        type: 'claymore',
      },
      {
        id: 65,
        name: 'Deathmatch',
        slug: 'deathmatch',
        rarity: '4',
        atk: 41,
        obtain: 'bp bounty',
        type: 'polearm',
      },
      {
        id: 66,
        name: 'Dragons Bane',
        slug: 'dragons-bane',
        rarity: '4',
        atk: 41,
        obtain: 'gacha',
        type: 'polearm',
      },
      {
        id: 81,
        name: 'Favonius Sword',
        slug: 'favonius-sword',
        rarity: '4',
        atk: 41,
        obtain: 'gacha',
        type: 'sword',
      },
      {
        id: 88,
        name: 'Sacrificial Sword',
        slug: 'sacrificial-sword',
        rarity: '4',
        atk: 41,
        obtain: 'gacha',
        type: 'sword',
      },
      {
        id: 5,
        name: 'Ebony Bow',
        slug: 'ebony-bow',
        rarity: '3',
        atk: 40,
        obtain: 'gacha',
        type: 'bow',
      },
      {
        id: 8,
        name: 'Messenger',
        slug: 'messenger',
        rarity: '3',
        atk: 40,
        obtain: 'chest',
        type: 'bow',
      },
      {
        id: 10,
        name: 'Raven Bow',
        slug: 'raven-bow',
        rarity: '3',
        atk: 40,
        obtain: 'gacha',
        type: 'bow',
      },
      {
        id: 21,
        name: 'Amber Catalyst',
        slug: 'amber-catalyst',
        rarity: '3',
        atk: 40,
        obtain: 'gacha',
        type: 'catalyst',
      },
      {
        id: 24,
        name: 'Emerald Orb',
        slug: 'emerald-orb',
        rarity: '3',
        atk: 40,
        obtain: 'gacha',
        type: 'catalyst',
      },
      {
        id: 39,
        name: 'Twin Nephrite',
        slug: 'twin-nephrite',
        rarity: '3',
        atk: 40,
        obtain: 'gacha',
        type: 'catalyst',
      },
      {
        id: 49,
        name: 'Quartz',
        slug: 'quartz',
        rarity: '3',
        atk: 40,
        obtain: 'gacha',
        type: 'claymore',
      },
      {
        id: 68,
        name: 'Halberd',
        slug: 'halberd',
        rarity: '3',
        atk: 40,
        obtain: 'gacha',
        type: 'polearm',
      },
      {
        id: 79,
        name: 'Dark Iron Sword',
        slug: 'dark-iron-sword',
        rarity: '3',
        atk: 40,
        obtain: 'gacha',
        type: 'sword',
      },
      {
        id: 95,
        name: 'Travelers Handy Sword',
        slug: 'travelers-handy-sword',
        rarity: '3',
        atk: 40,
        obtain: 'chest',
        type: 'sword',
      },
      {
        id: 16,
        name: 'Sharpshooters Oath',
        slug: 'sharpshooters-oath',
        rarity: '3',
        atk: 39,
        obtain: 'gacha',
        type: 'bow',
      },
      {
        id: 30,
        name: 'Otherworldly Story',
        slug: 'otherworldly-story',
        rarity: '3',
        atk: 39,
        obtain: 'gacha',
        type: 'catalyst',
      },
      {
        id: 38,
        name: 'Thrilling Tales of Dragon Slayers',
        slug: 'thrilling-tales-of-dragon-slayers',
        rarity: '3',
        atk: 39,
        obtain: 'gacha',
        type: 'catalyst',
      },
      {
        id: 43,
        name: 'Debate Club',
        slug: 'debate-club',
        rarity: '3',
        atk: 39,
        obtain: 'gacha',
        type: 'claymore',
      },
      {
        id: 45,
        name: 'Ferrous Shadow',
        slug: 'ferrous-shadow',
        rarity: '3',
        atk: 39,
        obtain: 'gacha',
        type: 'claymore',
      },
      {
        id: 54,
        name: 'Skyrider Greatsword',
        slug: 'skyrider-greatsword',
        rarity: '3',
        atk: 39,
        obtain: 'gacha',
        type: 'claymore',
      },
      {
        id: 58,
        name: 'White Iron Greatsword',
        slug: 'white-iron-greatsword',
        rarity: '3',
        atk: 39,
        obtain: 'gacha',
        type: 'claymore',
      },
      {
        id: 75,
        name: 'White Tassel',
        slug: 'white-tassel',
        rarity: '3',
        atk: 39,
        obtain: 'chest',
        type: 'polearm',
      },
      {
        id: 78,
        name: 'Cool Steel',
        slug: 'cool-steel',
        rarity: '3',
        atk: 39,
        obtain: 'gacha',
        type: 'sword',
      },
      {
        id: 82,
        name: 'Fillet Blade',
        slug: 'fillet-blade',
        rarity: '3',
        atk: 39,
        obtain: 'gacha',
        type: 'sword',
      },
      {
        id: 83,
        name: 'Harbinger of Dawn',
        slug: 'harbinger-of-dawn',
        rarity: '3',
        atk: 39,
        obtain: 'gacha',
        type: 'sword',
      },
      {
        id: 11,
        name: 'Recurve Bow',
        slug: 'recurve-bow',
        rarity: '3',
        atk: 38,
        obtain: 'chest',
        type: 'bow',
      },
      {
        id: 18,
        name: 'Slingshot',
        slug: 'slingshot',
        rarity: '3',
        atk: 38,
        obtain: 'gacha',
        type: 'bow',
      },
      {
        id: 28,
        name: 'Magic Guide',
        slug: 'magic-guide',
        rarity: '3',
        atk: 38,
        obtain: 'gacha',
        type: 'catalyst',
      },
      {
        id: 42,
        name: 'Bloodtainted Greatsword',
        slug: 'bloodtainted-greatsword',
        rarity: '3',
        atk: 38,
        obtain: 'gacha',
        type: 'claymore',
      },
      {
        id: 62,
        name: 'Black Tassel',
        slug: 'black-tassel',
        rarity: '3',
        atk: 38,
        obtain: 'gacha',
        type: 'polearm',
      },
      {
        id: 90,
        name: 'Skyrider Sword',
        slug: 'skyrider-sword',
        rarity: '3',
        atk: 38,
        obtain: 'gacha',
        type: 'sword',
      },
      {
        id: 15,
        name: 'Seasoned Hunters Bow',
        slug: 'seasoned-hunters-bow',
        rarity: '2',
        atk: 33,
        obtain: 'chest',
        type: 'bow',
      },
      {
        id: 31,
        name: 'Pocket Grimoire',
        slug: 'pocket-grimoire',
        rarity: '2',
        atk: 33,
        obtain: 'chest',
        type: 'catalyst',
      },
      {
        id: 47,
        name: 'Old Mercs Pal',
        slug: 'old-mercs-pal',
        rarity: '2',
        atk: 33,
        obtain: 'chest',
        type: 'claymore',
      },
      {
        id: 69,
        name: 'Iron Point',
        slug: 'iron-point',
        rarity: '2',
        atk: 33,
        obtain: 'chest',
        type: 'polearm',
      },
      {
        id: 89,
        name: 'Silver Sword',
        slug: 'silver-sword',
        rarity: '2',
        atk: 33,
        obtain: 'chest',
        type: 'sword',
      },
      {
        id: 7,
        name: 'Hunters Bow',
        slug: 'hunters-bow',
        rarity: '1',
        atk: 23,
        obtain: 'chest',
        type: 'bow',
      },
      {
        id: 22,
        name: 'Apprentices Notes',
        slug: 'apprentices-notes',
        rarity: '1',
        atk: 23,
        obtain: 'chest',
        type: 'catalyst',
      },
      {
        id: 57,
        name: 'Waster Greatsword',
        slug: 'waster-greatsword',
        rarity: '1',
        atk: 23,
        obtain: 'chest',
        type: 'claymore',
      },
      {
        id: 61,
        name: 'Beginners Protector',
        slug: 'beginners-protector',
        rarity: '1',
        atk: 23,
        obtain: 'chest',
        type: 'polearm',
      },
      {
        id: 80,
        name: 'Dull Blade',
        slug: 'dull-blade',
        rarity: '1',
        atk: 23,
        obtain: 'chest',
        type: 'sword',
      },
    ];
    const saveWeaponList = weaponList.map((weapon) => {
      const { id, name, slug, ...inf } = weapon;
      const information = JSON.stringify(inf);
      return {
        title: name,
        slug,
        information,
        type: TAG_TYPE.WEAPON,
      };
    });
    await queryRunner.manager
      .createQueryBuilder()
      .insert()
      .into('tag')
      .values(saveWeaponList)
      .execute();
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
